name: CD

on:
  push:
    branches:
      - main

concurrency:
  group: CD

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment:
      name: production
      url: https://richardharrahdotcom.fly.dev
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: superfly/flyctl-actions/setup-flyctl@ed8efb33836e8b2096c7fd3ba1c8afe303ebbff1 # master
        with:
          version: 0.2.8
      - run: flyctl deploy -c ./fly.toml --remote-only --build-secret="SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN" --build-arg="SENTRY_RELEASE=$GITHUB_SHA"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      - uses: getsentry/action-release@a74facf8a080ecbdf1cb355f16743530d712abb7 # v1.11.0
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: topplethenun
          SENTRY_PROJECT: richardharrahdotcom
        with:
          environment: production
